{% set name = "javaproperties" %}
{% set version = "0.8.2" %} 

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f780d17ca12d57da58519dcf9d821cbcdb6f98a8b5af661013e31a5050c59a0f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

test:
  source_files:
    - test
  imports:
    - javaproperties
  commands:
    - pip check
    - TZ=America/New_York pytest -v test  # [unix]
  requires:
    - pip
    - pytest
    - python-dateutil
    - pytest-mock

about:
  home: https://github.com/jwodder/javaproperties
  summary: Read & write Java .properties files
  description: Read & write Java .properties files
  license_family: MIT
  license: MIT
  license_file: LICENSE
  description: Read & write Java .properties files
  dev_url: https://github.com/jwodder/javaproperties
  doc_url: https://javaproperties.readthedocs.io

extra:
  recipe-maintainers:
    - janjagusch
